name: Build Android Native Library

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Run ndk-build
        run: |
          ndk-build

      - name: Upload compiled library
        uses: actions/upload-artifact@v4
        with:
          name: Meta4-libs
          path: libs/
